[package]
name = "triankl3/genesis-demo"
license = "MIT"
authors = ["triankl3"]
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dev-dependencies]
iris = "michael-48/iris@2.1.4"